# Generated by Django 3.2.5 on 2021-10-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=50)),
                ('developer_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
    ]
